spring:
  application:
    name: url-shortener-service
  config:
    import: configserver:http://localhost:8888/
  cloud:
    config:
      uri: http://localhost:8888  # URI of your Config Server
      fail-fast: true
  profiles:
    active: default

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

logging:
  level:
    org.springframework.cloud: DEBUG